### ISSUE TITLE
agent_001 and agent_002 communication not working

### ISSUE THREAD

**Issue by chrisnbattista** [hsfl/cosmos-core#41] opened 2020-10-16 05:45 UTC
Observed behavior: agent_001 and agent_002 do not communicate with each other running on the same vagrant machine
Expected behavior: agent_001 and agent_002 should connect and exchange information when run
System information: clean vagrant install using Github install instructions. dev branch

**Comment by jrlewis213** [comment] 2020-10-19 19:03
Duplicate of #42

**Closed by jrlewis213** 2020-10-19 19:03 UTC
